name: Repo Update
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21.3.0
      - name: Running script
        run: node index.js
      - name: Updating repo
        continue-on-error: true
        run: |
          git config --global user.name 'LaszloR1'
          git config --global user.email 'LaszloR1@users.noreply.github.com'
          git add article
          git commit -am "[WORKFLOW] Updating news."
          git push
