name: News Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21.3.0
      - name: Running script to gather the news.
        run: node index.js
      - name: Uploading news to the repo.
        continue-on-error: true
        run: |
          git config user.name "bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "[WORKFLOW] Updated news."
          git push
